// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using fmis.Data;

namespace fmis.Migrations.Obligation
{
    [DbContext(typeof(ObligationContext))]
    [Migration("20210730015828_Obligation")]
    partial class Obligation
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.8")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("fmis.Models.Obligation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Created_by")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date_recieved")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date_released")
                        .HasColumnType("datetime2");

                    b.Property<string>("Dv")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fund_source")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Gross")
                        .HasColumnType("real");

                    b.Property<int>("Ors_no")
                        .HasColumnType("int");

                    b.Property<string>("Particulars")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Payee")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Po_no")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pr_no")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Time_recieved")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Time_released")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Obligation");
                });
#pragma warning restore 612, 618
        }
    }
}
