// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using fmis.Data;

namespace fmis.Migrations
{
    [DbContext(typeof(MyDbContext))]
    partial class MyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.8")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("fmis.Models.Appropriation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Code")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Appropriation");
                });

            modelBuilder.Entity("fmis.Models.Budget.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Account");
                });

            modelBuilder.Entity("fmis.Models.Designation", b =>
                {
                    b.Property<int>("Did")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("Ors_headId")
                        .HasColumnType("int");

                    b.Property<string>("Remember_Token")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Requesting_officeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Updated_At")
                        .HasColumnType("datetime2");

                    b.HasKey("Did");

                    b.HasIndex("Ors_headId");

                    b.HasIndex("Requesting_officeId");

                    b.ToTable("Designation");
                });

            modelBuilder.Entity("fmis.Models.Division", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Head")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Remember_Token")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated_At")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Division");
                });

            modelBuilder.Entity("fmis.Models.FundsRealignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("FundSourceAmountId")
                        .HasColumnType("int");

                    b.Property<int?>("FundSourceId")
                        .HasColumnType("int");

                    b.Property<decimal>("Realignment_amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Realignment_to")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("token")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FundSourceAmountId");

                    b.HasIndex("FundSourceId");

                    b.ToTable("FundsRealignment");
                });

            modelBuilder.Entity("fmis.Models.John.AllotmentClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Account_Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Allotment_Class")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("AllotmentClass");
                });

            modelBuilder.Entity("fmis.Models.John.FundSource", b =>
                {
                    b.Property<int>("FundSourceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Beginning_balance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("BudgetAllotmentId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FundSourceTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FundSourceTitleCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ObligationId")
                        .HasColumnType("int");

                    b.Property<int>("PrexcId")
                        .HasColumnType("int");

                    b.Property<decimal>("Remaining_balance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Respo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SummaryReportId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UtilizationId")
                        .HasColumnType("int");

                    b.Property<decimal>("obligated_amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("realignment_amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("token")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("utilized_amount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("FundSourceId");

                    b.HasIndex("BudgetAllotmentId");

                    b.HasIndex("ObligationId");

                    b.HasIndex("PrexcId");

                    b.HasIndex("SummaryReportId");

                    b.HasIndex("UtilizationId");

                    b.ToTable("FundSource");
                });

            modelBuilder.Entity("fmis.Models.John.FundSourceAmount", b =>
                {
                    b.Property<int>("FundSourceAmountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BudgetAllotmentId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("FundSourceId")
                        .HasColumnType("int");

                    b.Property<int?>("PrexcId")
                        .HasColumnType("int");

                    b.Property<int>("UacsId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("beginning_balance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("fundsource_amount_token")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("fundsource_token")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("realignment_amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("remaining_balance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FundSourceAmountId");

                    b.HasIndex("FundSourceId");

                    b.HasIndex("PrexcId");

                    b.HasIndex("UacsId");

                    b.ToTable("FundSourceAmount");
                });

            modelBuilder.Entity("fmis.Models.Logs", b =>
                {
                    b.Property<int>("LogsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("FundSourceId")
                        .HasColumnType("int");

                    b.Property<int>("SubAllotmentId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("created_designation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("created_division")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("created_id")
                        .HasColumnType("int");

                    b.Property<string>("created_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("created_section")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("logs_type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("source_type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LogsId");

                    b.ToTable("Logs");
                });

            modelBuilder.Entity("fmis.Models.Obligation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Created_by")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date_recieved")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date_released")
                        .HasColumnType("datetime2");

                    b.Property<string>("Dv")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Gross")
                        .HasColumnType("real");

                    b.Property<int>("Ors_no")
                        .HasColumnType("int");

                    b.Property<string>("Particulars")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Payee")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Po_no")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pr_no")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Time_recieved")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Time_released")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("obligation_token")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("source_id")
                        .HasColumnType("int");

                    b.Property<string>("source_type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Obligation");
                });

            modelBuilder.Entity("fmis.Models.ObligationAmount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("Expense_code")
                        .HasColumnType("bigint");

                    b.Property<int?>("FundSourceId")
                        .HasColumnType("int");

                    b.Property<int>("ObligationId")
                        .HasColumnType("int");

                    b.Property<int?>("SubAllotmentId")
                        .HasColumnType("int");

                    b.Property<float>("Total_disbursement")
                        .HasColumnType("real");

                    b.Property<float>("Total_net_amount")
                        .HasColumnType("real");

                    b.Property<float>("Total_others")
                        .HasColumnType("real");

                    b.Property<float>("Total_tax_amount")
                        .HasColumnType("real");

                    b.Property<int>("UacsId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("obligation_amount_token")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("obligation_token")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FundSourceId");

                    b.HasIndex("ObligationId");

                    b.HasIndex("SubAllotmentId");

                    b.ToTable("ObligationAmount");
                });

            modelBuilder.Entity("fmis.Models.Ors_head", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Personalinfo_userid")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Ors_head");
                });

            modelBuilder.Entity("fmis.Models.Personal_Information", b =>
                {
                    b.Property<int>("Pid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Budget_allotmentBudgetAllotmentId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Ors_headId")
                        .HasColumnType("int");

                    b.Property<int?>("Requesting_officeId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("designation")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("division")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("full_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("section")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("userid")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Pid");

                    b.HasIndex("Budget_allotmentBudgetAllotmentId");

                    b.HasIndex("Ors_headId");

                    b.HasIndex("Requesting_officeId");

                    b.ToTable("Personal_Information");
                });

            modelBuilder.Entity("fmis.Models.Prexc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("SummaryReportId")
                        .HasColumnType("int");

                    b.Property<int?>("UacsId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("pap_code1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pap_code2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pap_title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("token")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SummaryReportId");

                    b.HasIndex("UacsId");

                    b.ToTable("Prexc");
                });

            modelBuilder.Entity("fmis.Models.Requesting_office", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("pi_userid")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Requesting_office");
                });

            modelBuilder.Entity("fmis.Models.Section", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Division")
                        .HasColumnType("int");

                    b.Property<string>("Head")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Remember_Token")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated_At")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Section");
                });

            modelBuilder.Entity("fmis.Models.SubAllotment_Realignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Realignment_amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Realignment_to")
                        .HasColumnType("int");

                    b.Property<int?>("SubAllotmentAmountId")
                        .HasColumnType("int");

                    b.Property<int?>("SubAllotmentId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("token")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SubAllotmentAmountId");

                    b.HasIndex("SubAllotmentId");

                    b.ToTable("SubAllotment_Realignment");
                });

            modelBuilder.Entity("fmis.Models.Sub_allotment", b =>
                {
                    b.Property<int>("SubAllotmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Beginning_balance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("BudgetAllotmentId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ObligationId")
                        .HasColumnType("int");

                    b.Property<decimal>("Remaining_balance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Responsibility_number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Suballotment_code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Suballotment_title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UtilizationId")
                        .HasColumnType("int");

                    b.Property<decimal>("obligated_amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("prexcId")
                        .HasColumnType("int");

                    b.Property<decimal>("realignment_amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("token")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("utilized_amount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("SubAllotmentId");

                    b.HasIndex("BudgetAllotmentId");

                    b.HasIndex("ObligationId");

                    b.HasIndex("UtilizationId");

                    b.HasIndex("prexcId")
                        .IsUnique();

                    b.ToTable("Sub_allotment");
                });

            modelBuilder.Entity("fmis.Models.Suballotment_amount", b =>
                {
                    b.Property<int>("SubAllotmentAmountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BudgetAllotmentId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("SubAllotmentId")
                        .HasColumnType("int");

                    b.Property<int>("UacsId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("beginning_balance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("realignment_amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("remaining_balance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("suballotment_amount_token")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("suballotment_token")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SubAllotmentAmountId");

                    b.HasIndex("SubAllotmentId");

                    b.HasIndex("UacsId");

                    b.ToTable("Suballotment_amount");
                });

            modelBuilder.Entity("fmis.Models.Uacs", b =>
                {
                    b.Property<int>("UacsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Account_title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Expense_code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FundSourceId")
                        .HasColumnType("int");

                    b.Property<int?>("ObligationId")
                        .HasColumnType("int");

                    b.Property<int?>("Sub_allotmentSubAllotmentId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UtilizationId")
                        .HasColumnType("int");

                    b.Property<string>("status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("token")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UacsId");

                    b.HasIndex("FundSourceId");

                    b.HasIndex("ObligationId");

                    b.HasIndex("Sub_allotmentSubAllotmentId");

                    b.HasIndex("UtilizationId");

                    b.ToTable("Uacs");
                });

            modelBuilder.Entity("fmis.Models.Utilization", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("datetime2");

                    b.Property<int>("Created_by")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date_recieved")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date_released")
                        .HasColumnType("datetime2");

                    b.Property<string>("Dv")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Gross")
                        .HasColumnType("real");

                    b.Property<int>("Ors_no")
                        .HasColumnType("int");

                    b.Property<string>("Particulars")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Payee")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Po_no")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pr_no")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Time_recieved")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Time_released")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Updated_At")
                        .HasColumnType("datetime2");

                    b.Property<int>("source_id")
                        .HasColumnType("int");

                    b.Property<string>("source_type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("utilization_token")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Utilization");
                });

            modelBuilder.Entity("fmis.Models.UtilizationAmount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("Expense_code")
                        .HasColumnType("bigint");

                    b.Property<int?>("FundSourceId")
                        .HasColumnType("int");

                    b.Property<int?>("SubAllotmentId")
                        .HasColumnType("int");

                    b.Property<float>("Total_disbursement")
                        .HasColumnType("real");

                    b.Property<float>("Total_net_amount")
                        .HasColumnType("real");

                    b.Property<float>("Total_others")
                        .HasColumnType("real");

                    b.Property<float>("Total_tax_amount")
                        .HasColumnType("real");

                    b.Property<int>("UacsId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UtilizationId")
                        .HasColumnType("int");

                    b.Property<string>("status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("utilization_amount_token")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("utilization_token")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FundSourceId");

                    b.HasIndex("SubAllotmentId");

                    b.HasIndex("UtilizationId");

                    b.ToTable("UtilizationAmount");
                });

            modelBuilder.Entity("fmis.Models.Yearly_reference", b =>
                {
                    b.Property<int>("YearlyReferenceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("YearlyReference")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("YearlyReferenceId");

                    b.ToTable("Yearly_reference");
                });

            modelBuilder.Entity("fmis.Models.silver.BudgetAllotment", b =>
                {
                    b.Property<int>("BudgetAllotmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Allotment_code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Allotment_series")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Allotment_title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("YearlyReferenceId")
                        .HasColumnType("int");

                    b.HasKey("BudgetAllotmentId");

                    b.HasIndex("YearlyReferenceId");

                    b.ToTable("BudgetAllotment");
                });

            modelBuilder.Entity("fmis.Models.silver.ManageUsers", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("RememberMe")
                        .HasColumnType("bit");

                    b.Property<string>("ReturnUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserRole")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ManageUsers");
                });

            modelBuilder.Entity("fmis.Models.silver.SummaryReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("SummaryReports")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UacsId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("datefrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("dateto")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("UacsId");

                    b.ToTable("SummaryReport");
                });

            modelBuilder.Entity("fmis.Models.Designation", b =>
                {
                    b.HasOne("fmis.Models.Ors_head", "Ors_head")
                        .WithMany()
                        .HasForeignKey("Ors_headId");

                    b.HasOne("fmis.Models.Requesting_office", "Requesting_office")
                        .WithMany()
                        .HasForeignKey("Requesting_officeId");

                    b.Navigation("Ors_head");

                    b.Navigation("Requesting_office");
                });

            modelBuilder.Entity("fmis.Models.FundsRealignment", b =>
                {
                    b.HasOne("fmis.Models.John.FundSourceAmount", "FundSourceAmount")
                        .WithMany()
                        .HasForeignKey("FundSourceAmountId");

                    b.HasOne("fmis.Models.John.FundSource", "FundSource")
                        .WithMany("FundsRealignment")
                        .HasForeignKey("FundSourceId");

                    b.Navigation("FundSource");

                    b.Navigation("FundSourceAmount");
                });

            modelBuilder.Entity("fmis.Models.John.FundSource", b =>
                {
                    b.HasOne("fmis.Models.silver.BudgetAllotment", "BudgetAllotment")
                        .WithMany("FundSources")
                        .HasForeignKey("BudgetAllotmentId");

                    b.HasOne("fmis.Models.Obligation", null)
                        .WithMany("FundSource")
                        .HasForeignKey("ObligationId");

                    b.HasOne("fmis.Models.Prexc", "Prexc")
                        .WithMany()
                        .HasForeignKey("PrexcId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("fmis.Models.silver.SummaryReport", null)
                        .WithMany("FundSources")
                        .HasForeignKey("SummaryReportId");

                    b.HasOne("fmis.Models.Utilization", null)
                        .WithMany("FundSource")
                        .HasForeignKey("UtilizationId");

                    b.Navigation("BudgetAllotment");

                    b.Navigation("Prexc");
                });

            modelBuilder.Entity("fmis.Models.John.FundSourceAmount", b =>
                {
                    b.HasOne("fmis.Models.John.FundSource", "FundSource")
                        .WithMany("FundSourceAmounts")
                        .HasForeignKey("FundSourceId");

                    b.HasOne("fmis.Models.Prexc", null)
                        .WithMany("FundSourceAmounts")
                        .HasForeignKey("PrexcId");

                    b.HasOne("fmis.Models.Uacs", "Uacs")
                        .WithMany()
                        .HasForeignKey("UacsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FundSource");

                    b.Navigation("Uacs");
                });

            modelBuilder.Entity("fmis.Models.ObligationAmount", b =>
                {
                    b.HasOne("fmis.Models.John.FundSource", "fundSource")
                        .WithMany()
                        .HasForeignKey("FundSourceId");

                    b.HasOne("fmis.Models.Obligation", null)
                        .WithMany("ObligationAmounts")
                        .HasForeignKey("ObligationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("fmis.Models.Sub_allotment", "SubAllotment")
                        .WithMany()
                        .HasForeignKey("SubAllotmentId");

                    b.Navigation("fundSource");

                    b.Navigation("SubAllotment");
                });

            modelBuilder.Entity("fmis.Models.Personal_Information", b =>
                {
                    b.HasOne("fmis.Models.silver.BudgetAllotment", "Budget_allotment")
                        .WithMany("Personal_Information")
                        .HasForeignKey("Budget_allotmentBudgetAllotmentId");

                    b.HasOne("fmis.Models.Ors_head", "Ors_head")
                        .WithMany()
                        .HasForeignKey("Ors_headId");

                    b.HasOne("fmis.Models.Requesting_office", "Requesting_office")
                        .WithMany()
                        .HasForeignKey("Requesting_officeId");

                    b.Navigation("Budget_allotment");

                    b.Navigation("Ors_head");

                    b.Navigation("Requesting_office");
                });

            modelBuilder.Entity("fmis.Models.Prexc", b =>
                {
                    b.HasOne("fmis.Models.silver.SummaryReport", null)
                        .WithMany("Prexc")
                        .HasForeignKey("SummaryReportId");

                    b.HasOne("fmis.Models.Uacs", "Uacs")
                        .WithMany()
                        .HasForeignKey("UacsId");

                    b.Navigation("Uacs");
                });

            modelBuilder.Entity("fmis.Models.SubAllotment_Realignment", b =>
                {
                    b.HasOne("fmis.Models.Suballotment_amount", "SubAllotmentAmount")
                        .WithMany()
                        .HasForeignKey("SubAllotmentAmountId");

                    b.HasOne("fmis.Models.Sub_allotment", "SubAllotment")
                        .WithMany("SubAllotmentRealignment")
                        .HasForeignKey("SubAllotmentId");

                    b.Navigation("SubAllotment");

                    b.Navigation("SubAllotmentAmount");
                });

            modelBuilder.Entity("fmis.Models.Sub_allotment", b =>
                {
                    b.HasOne("fmis.Models.silver.BudgetAllotment", "Budget_allotment")
                        .WithMany("Sub_allotments")
                        .HasForeignKey("BudgetAllotmentId");

                    b.HasOne("fmis.Models.Obligation", null)
                        .WithMany("SubAllotment")
                        .HasForeignKey("ObligationId");

                    b.HasOne("fmis.Models.Utilization", null)
                        .WithMany("SubAllotment")
                        .HasForeignKey("UtilizationId");

                    b.HasOne("fmis.Models.Prexc", "prexc")
                        .WithOne("Sub_Allotment")
                        .HasForeignKey("fmis.Models.Sub_allotment", "prexcId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Budget_allotment");

                    b.Navigation("prexc");
                });

            modelBuilder.Entity("fmis.Models.Suballotment_amount", b =>
                {
                    b.HasOne("fmis.Models.Sub_allotment", "SubAllotment")
                        .WithMany("SubAllotmentAmounts")
                        .HasForeignKey("SubAllotmentId");

                    b.HasOne("fmis.Models.Uacs", "Uacs")
                        .WithMany()
                        .HasForeignKey("UacsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SubAllotment");

                    b.Navigation("Uacs");
                });

            modelBuilder.Entity("fmis.Models.Uacs", b =>
                {
                    b.HasOne("fmis.Models.John.FundSource", null)
                        .WithMany("Uacs")
                        .HasForeignKey("FundSourceId");

                    b.HasOne("fmis.Models.Obligation", null)
                        .WithMany("Uacs")
                        .HasForeignKey("ObligationId");

                    b.HasOne("fmis.Models.Sub_allotment", null)
                        .WithMany("Uacs")
                        .HasForeignKey("Sub_allotmentSubAllotmentId");

                    b.HasOne("fmis.Models.Utilization", null)
                        .WithMany("Uacs")
                        .HasForeignKey("UtilizationId");
                });

            modelBuilder.Entity("fmis.Models.UtilizationAmount", b =>
                {
                    b.HasOne("fmis.Models.John.FundSource", "fundSource")
                        .WithMany()
                        .HasForeignKey("FundSourceId");

                    b.HasOne("fmis.Models.Sub_allotment", "SubAllotment")
                        .WithMany()
                        .HasForeignKey("SubAllotmentId");

                    b.HasOne("fmis.Models.Utilization", null)
                        .WithMany("UtilizationAmount")
                        .HasForeignKey("UtilizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("fundSource");

                    b.Navigation("SubAllotment");
                });

            modelBuilder.Entity("fmis.Models.silver.BudgetAllotment", b =>
                {
                    b.HasOne("fmis.Models.Yearly_reference", "Yearly_reference")
                        .WithMany("BudgetAllotments")
                        .HasForeignKey("YearlyReferenceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Yearly_reference");
                });

            modelBuilder.Entity("fmis.Models.silver.SummaryReport", b =>
                {
                    b.HasOne("fmis.Models.Uacs", "Uacs")
                        .WithMany()
                        .HasForeignKey("UacsId");

                    b.Navigation("Uacs");
                });

            modelBuilder.Entity("fmis.Models.John.FundSource", b =>
                {
                    b.Navigation("FundSourceAmounts");

                    b.Navigation("FundsRealignment");

                    b.Navigation("Uacs");
                });

            modelBuilder.Entity("fmis.Models.Obligation", b =>
                {
                    b.Navigation("FundSource");

                    b.Navigation("ObligationAmounts");

                    b.Navigation("SubAllotment");

                    b.Navigation("Uacs");
                });

            modelBuilder.Entity("fmis.Models.Prexc", b =>
                {
                    b.Navigation("FundSourceAmounts");

                    b.Navigation("Sub_Allotment");
                });

            modelBuilder.Entity("fmis.Models.Sub_allotment", b =>
                {
                    b.Navigation("SubAllotmentAmounts");

                    b.Navigation("SubAllotmentRealignment");

                    b.Navigation("Uacs");
                });

            modelBuilder.Entity("fmis.Models.Utilization", b =>
                {
                    b.Navigation("FundSource");

                    b.Navigation("SubAllotment");

                    b.Navigation("Uacs");

                    b.Navigation("UtilizationAmount");
                });

            modelBuilder.Entity("fmis.Models.Yearly_reference", b =>
                {
                    b.Navigation("BudgetAllotments");
                });

            modelBuilder.Entity("fmis.Models.silver.BudgetAllotment", b =>
                {
                    b.Navigation("FundSources");

                    b.Navigation("Personal_Information");

                    b.Navigation("Sub_allotments");
                });

            modelBuilder.Entity("fmis.Models.silver.SummaryReport", b =>
                {
                    b.Navigation("FundSources");

                    b.Navigation("Prexc");
                });
#pragma warning restore 612, 618
        }
    }
}
