// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using fmis.Data;

namespace fmis.Migrations.MyDb
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20210906024826_MyDb")]
    partial class MyDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.8")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("fmis.Models.Budget_allotment", b =>
                {
                    b.Property<int>("BudgetAllotmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Allotment_code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Allotment_series")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Allotment_title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Updated_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("Year")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BudgetAllotmentId");

                    b.ToTable("Budget_allotment");
                });

            modelBuilder.Entity("fmis.Models.John.FundSource", b =>
                {
                    b.Property<int>("FundSourceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Budget_allotmentBudgetAllotmentId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FundSourceTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FundSourceTitleCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrexcCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Respo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FundSourceId");

                    b.HasIndex("Budget_allotmentBudgetAllotmentId");

                    b.ToTable("FundSource");
                });

            modelBuilder.Entity("fmis.Models.John.FundSource", b =>
                {
                    b.HasOne("fmis.Models.Budget_allotment", "Budget_allotment")
                        .WithMany("FundSources")
                        .HasForeignKey("Budget_allotmentBudgetAllotmentId");

                    b.Navigation("Budget_allotment");
                });

            modelBuilder.Entity("fmis.Models.Budget_allotment", b =>
                {
                    b.Navigation("FundSources");
                });
#pragma warning restore 612, 618
        }
    }
}
